name: Deploy BaseRep Protocol

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean Build and Restart
        run: |
          cd /home/vps/baserep-protocol
          git pull origin main
          npm install
          # Nettoyage pour éviter les styles CSS cassés
          rm -rf .next
          npm run build
          # Redémarrage de l'app sur le port 3000
          pm2 restart baserep || pm2 start npm --name "baserep" -- start
          pm2 save
